name: PowerBI Deployment
 
on:
  push:
    branches:
      - development
 
jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
 
    - name: Install Power BI PowerShell Module
      run: Install-Module -Name MicrosoftPowerBIMgmt -Force -AllowClobber -Scope CurrentUser
 
    - name: Run PowerShell Script
      env:
        POWERBI_USERNAME: ${{ secrets.POWERBI_USERNAME }}
        POWERBI_PASSWORD: ${{ secrets.POWERBI_PASSWORD }}
      run: |
        # Run your PowerShell script here to deploy Power BI reports
        .\deploy-powerbi-reports.ps1
