name: Power BI CI/CD

on:
  push:
    branches:
      - main  # Adjust this according to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Power BI CLI
        run: |
          npm install -g powerbi-cli

      - name: Deploy Power BI reports
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          WORKSPACE_ID: ${{ secrets.WORKSPACE_ID }}
        run: |
          pbi import -f "path/to/your/report.pbix" -w $WORKSPACE_ID -t $TENANT_ID -i $CLIENT_ID -s $CLIENT_SECRET
