name: Power BI CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy-powerbi-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Report to Power BI
        uses: powerbi-actions/deploy-report@v1
        with:
          tenantId: ${{ vars.AZURE_TENANT_ID }}
          clientId: ${{ vars.AZURE_CLIENT_ID }}
          clientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
          workspaceId: ${{ secrets.POWERBI_WORKSPACE_ID }}
          reportFilePath: 'Power BI Assignment.pbix'
