name: Power BI CI/CD

on:
  push:
    branches:
      - main  # Adjust this according to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Power BI CLI
        run: |
          npm install -g powerbi-cli

      - name: Deploy Power BI reports
        env:
          TENANT_ID: ${{ vars.TENANT_ID }}
          CLIENT_ID: ${{ vars.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          WORKSPACE_ID: ${{ secrets.WORKSPACE_ID }}
        run: |
          pbi import -f "path/to/your/report.pbix" -w ${{ secrets.WORKSPACE_ID }} -t ${{ vars.TENANT_ID }} -i ${{ vars.CLIENT_ID }}D -s ${{ secrets.CLIENT_SECRET }}
